apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-health-check          # ⚠️ este nombre debe coincidir
  namespace: devops-challenge      # ⚠️ este namespace también
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-health-check
  template:
    metadata:
      labels:
        app: node-health-check
    spec:
      containers:
        - name: app
          image: node-health-check:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
