apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-health-check
  namespace: devops-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-health-check
  template:
    metadata:
      labels:
        app: node-health-check
    spec:
      containers:
        - name: node-health-check
          image: node-health-check:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
