apiVersion: v1               # Versión de la API de Kubernetes para recursos básicos como Secret
kind: Secret                 # Tipo de recurso: Secret (se usa para almacenar información sensible)

metadata:
  name: app-secrets          # Nombre del secret
  namespace: devops-challenge # Namespace donde se crea el secret

type: Opaque                 # Tipo de secret genérico (usado para datos arbitrarios codificados en base64)

data:
  dummy: ZGVtbw==            # Clave "dummy" con valor "demo" codificado en base64
