apiVersion: v1
kind: Service
metadata:
  name: node-health-check
  namespace: devops-challenge
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
