apiVersion: v1
kind: Service
metadata:
  name: node-health-check
  namespace: devops-challenge
spec:
  selector:
    app: node-health-check
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
