apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: devops-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: node-app
          imagePullPolicy: Never  # 🔧 evita que busque la imagen en Docker Hub
          command: ["node", "index.js"]
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: api_key
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
